### ISSUE TITLE
I can call the function as static

### ISSUE THREAD

**Issue by closerdesign** [hocza/sendy-laravel#13]
Hi guys,

I'm trying to use the library following your instructions but at the end, the only response that I have is that I'm trying to call a method statically that can't be called that way. Any idea?

**Comment by alisonmonteiro** [comment]
Hi, @closerdesign 
How are you? Could you, please, post your code here? 
I mean, the part which is causing this error.

Tks!

**Comment by closerdesign** [comment]
Thanks!

I'm having to do this:

$sendy = new Sendy([
    'listId' => 'MyListId',
    'installationUrl' => 'MyUrl',
    'apiKey' => 'MyApiKey'
]);

$sendy->subscribe([
    'email' => $request->email
]);

Instead of this:

$data = [    'email' => 'johndoe@example.com',    'name' => 'John
Doe',    'any_custom_column' => 'value'];Sendy::subscribe($data);

**Comment by hocza** [comment]
Huh next time hide your API key.

So the first snippet is working but the below one is not working?

Did you setup the config/sendy.php correctly?

**Comment by closerdesign** [comment]
Yes. And there is no problem at that point. The thing is that is I use the
function as static it doesn't work. If I use the function as dynamic it
simply ignores the sendy.php.

**Comment by alisonmonteiro** [comment]
@closerdesign To use the method as static you need add an alias on `config/app.php`

``` php
'aliases' => [
    // ...
    'Sendy' => 'Hocza\Sendy\Facades\Sendy',
]
```

Did you do that?

**Comment by closerdesign** [comment]
Yes, I did. It didn´t work. I followed the instructions exactly as they are on the site.

A question comes up with this, what´s the difference between these formats on service providers?

'View' => Illuminate\Support\Facades\View::class,
'Sendy' => 'Hocza\Sendy\Facades\Sendy',

Do I have to call Sendy the same way as View?

Thanks dude!

**Comment by juanmrad** [comment]
@closerdesign if you still might have the issue I was able to fix it by doing:
`use Hocza\Sendy\Facades\Sendy;`
Instead and then call the functions statically. It complains in php storm that the function doesn't exist but it works fine.
